-- Initial GAARD metadata schema. Keep it aligned with the current ORM models.
-- This file is executed only when the metadata database contains no tables.

-- dialect: sqlite
CREATE TABLE IF NOT EXISTS admin_audit_logs (id INTEGER NOT NULL, occurred_at DATETIME NOT NULL, actor VARCHAR(255) NOT NULL, action VARCHAR(255) NOT NULL, resource_type VARCHAR(255) NOT NULL, resource_id VARCHAR(255) NOT NULL, details_json TEXT NOT NULL, PRIMARY KEY (id));
CREATE TABLE IF NOT EXISTS admin_sessions (id INTEGER NOT NULL, token_hash VARCHAR(128) NOT NULL, user_id INTEGER NOT NULL, username VARCHAR(255) NOT NULL, role VARCHAR(50) NOT NULL, auth_provider VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, last_seen DATETIME NOT NULL, PRIMARY KEY (id));
CREATE UNIQUE INDEX IF NOT EXISTS ix_admin_sessions_token_hash ON admin_sessions (token_hash);
CREATE TABLE IF NOT EXISTS admin_settings ("key" VARCHAR(255) NOT NULL, value TEXT NOT NULL, updated_at DATETIME NOT NULL, updated_by VARCHAR(255) NOT NULL, PRIMARY KEY ("key"));
CREATE TABLE IF NOT EXISTS admin_users (id INTEGER NOT NULL, username VARCHAR(255) NOT NULL, display_name VARCHAR(255) NOT NULL, auth_provider VARCHAR(255) NOT NULL, role VARCHAR(50) NOT NULL, is_system_admin BOOLEAN NOT NULL, enterprise_access BOOLEAN NOT NULL, password_hash TEXT NOT NULL, must_change_password BOOLEAN NOT NULL, is_provisioned BOOLEAN NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, PRIMARY KEY (id), CONSTRAINT uq_admin_users_auth_provider_username UNIQUE (auth_provider, username));
CREATE TABLE IF NOT EXISTS analysis_sessions (id INTEGER NOT NULL, session_id VARCHAR(64) NOT NULL, status VARCHAR(50) NOT NULL, user_id VARCHAR(255) NOT NULL, datasource_id VARCHAR(255) NOT NULL, question TEXT NOT NULL, context_json TEXT NOT NULL, events_json TEXT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, PRIMARY KEY (id));
CREATE UNIQUE INDEX IF NOT EXISTS ix_analysis_sessions_session_id ON analysis_sessions (session_id);
CREATE TABLE IF NOT EXISTS business_knowledge_claims (id INTEGER NOT NULL, connector_id INTEGER NOT NULL, knowledge_type VARCHAR(100) NOT NULL, status VARCHAR(50) NOT NULL, claim_text TEXT NOT NULL, subject_json TEXT NOT NULL, evidence_json TEXT NOT NULL, confidence FLOAT NOT NULL, source VARCHAR(100) NOT NULL, request_id VARCHAR(255) NOT NULL, audit_reference VARCHAR(255) NOT NULL, requires_approval BOOLEAN NOT NULL, created_at DATETIME NOT NULL, last_verified_at DATETIME, updated_at DATETIME NOT NULL, updated_by VARCHAR(255) NOT NULL, PRIMARY KEY (id));
CREATE TABLE IF NOT EXISTS business_logic_suggestions (id INTEGER NOT NULL, connector_id INTEGER NOT NULL, source_audit_id INTEGER, status VARCHAR(50) NOT NULL, safety VARCHAR(50) NOT NULL, enabled BOOLEAN NOT NULL, error_category VARCHAR(100) NOT NULL, title VARCHAR(255) NOT NULL, rule_text TEXT NOT NULL, terms_json TEXT NOT NULL, join_hints_json TEXT NOT NULL, failed_identifier VARCHAR(255) NOT NULL, repaired_identifier VARCHAR(255) NOT NULL, confidence FLOAT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, updated_by VARCHAR(255) NOT NULL, PRIMARY KEY (id));
CREATE TABLE IF NOT EXISTS conversation_turns (id INTEGER NOT NULL, turn_id VARCHAR(64) NOT NULL, conversation_id VARCHAR(64) NOT NULL, mode VARCHAR(50) NOT NULL, status VARCHAR(50) NOT NULL, original_question TEXT NOT NULL, standalone_question TEXT NOT NULL, answer TEXT NOT NULL, sql TEXT NOT NULL, metadata_json TEXT NOT NULL, data_query_audit_id INTEGER, analysis_session_id VARCHAR(64) NOT NULL, context_decision VARCHAR(50) NOT NULL, context_confidence FLOAT NOT NULL, created_at DATETIME NOT NULL, PRIMARY KEY (id));
CREATE UNIQUE INDEX IF NOT EXISTS ix_conversation_turns_turn_id ON conversation_turns (turn_id);
CREATE TABLE IF NOT EXISTS conversations (id INTEGER NOT NULL, conversation_id VARCHAR(64) NOT NULL, owner_user_id VARCHAR(255) NOT NULL, owner_username VARCHAR(255) NOT NULL, status VARCHAR(50) NOT NULL, datasource_id VARCHAR(255) NOT NULL, datasource_ids_json TEXT NOT NULL, title VARCHAR(255) NOT NULL, summary_json TEXT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, PRIMARY KEY (id));
CREATE UNIQUE INDEX IF NOT EXISTS ix_conversations_conversation_id ON conversations (conversation_id);
CREATE TABLE IF NOT EXISTS dashboard_user_states (owner_user_id VARCHAR(255) NOT NULL, owner_username VARCHAR(255) NOT NULL, active_dashboard_id VARCHAR(64) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, PRIMARY KEY (owner_user_id));
CREATE TABLE IF NOT EXISTS dashboard_shares (id INTEGER NOT NULL, dashboard_id VARCHAR(64) NOT NULL, target_user_id VARCHAR(255) NOT NULL, target_username VARCHAR(255) NOT NULL, access_level VARCHAR(20) NOT NULL, created_by_user_id VARCHAR(255) NOT NULL, created_by_username VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, PRIMARY KEY (id), CONSTRAINT uq_dashboard_shares_dashboard_target UNIQUE (dashboard_id, target_user_id));
CREATE TABLE IF NOT EXISTS dashboard_widgets (id INTEGER NOT NULL, widget_id VARCHAR(64) NOT NULL, dashboard_id VARCHAR(64) NOT NULL, owner_user_id VARCHAR(255) NOT NULL, owner_username VARCHAR(255) NOT NULL, metric_widget_key VARCHAR(255) NOT NULL, title VARCHAR(255) NOT NULL, visualization_type VARCHAR(50) NOT NULL, x INTEGER NOT NULL, y INTEGER NOT NULL, w INTEGER NOT NULL, h INTEGER NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, PRIMARY KEY (id), CONSTRAINT uq_dashboard_widgets_widget_id UNIQUE (widget_id));
CREATE TABLE IF NOT EXISTS dashboards (id INTEGER NOT NULL, dashboard_id VARCHAR(64) NOT NULL, owner_user_id VARCHAR(255) NOT NULL, owner_username VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, description TEXT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, PRIMARY KEY (id));
CREATE UNIQUE INDEX IF NOT EXISTS ix_dashboards_dashboard_id ON dashboards (dashboard_id);
CREATE TABLE IF NOT EXISTS data_query_audit_logs (id INTEGER NOT NULL, occurred_at DATETIME NOT NULL, type VARCHAR(50) NOT NULL, user_id VARCHAR(255) NOT NULL, datasource_id VARCHAR(255) NOT NULL, question TEXT NOT NULL, answer TEXT NOT NULL, sql TEXT NOT NULL, llm_sql_language VARCHAR(50) NOT NULL, output_classification VARCHAR(50) NOT NULL, metadata_json TEXT NOT NULL, PRIMARY KEY (id), CONSTRAINT data_query_audit_type CHECK (type IN ('info', 'sql_error', 'access_error')), CONSTRAINT output_classification CHECK (output_classification IN ('personal_data', 'sensitive_data', 'technical_data', 'neutral_data', 'unknown')));
CREATE TABLE IF NOT EXISTS database_migration_tags (tag VARCHAR(255) NOT NULL, applied_at DATETIME NOT NULL, PRIMARY KEY (tag));
CREATE TABLE IF NOT EXISTS datasource_connectors (id INTEGER NOT NULL, connector_key VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, database_type VARCHAR(50) NOT NULL, database_url TEXT NOT NULL, sql_dialect VARCHAR(50) NOT NULL, active BOOLEAN NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, updated_by VARCHAR(255) NOT NULL, PRIMARY KEY (id), CONSTRAINT uq_datasource_connectors_key UNIQUE (connector_key));
UPDATE datasource_connectors SET database_type = 'duckdb-file' WHERE database_type = 'duckdb-excel';
UPDATE datasource_connectors SET database_url = REPLACE(database_url, 'duckdb-excel://', 'duckdb-file://') WHERE database_url LIKE 'duckdb-excel://%';
CREATE TABLE IF NOT EXISTS datasource_schema_caches (connector_id INTEGER NOT NULL, schema_json TEXT NOT NULL, table_settings_json TEXT NOT NULL, formatted_schema TEXT NOT NULL, introspected_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, updated_by VARCHAR(255) NOT NULL, PRIMARY KEY (connector_id));
CREATE TABLE IF NOT EXISTS overview_widgets (id INTEGER NOT NULL, widget_key VARCHAR(255) NOT NULL, label VARCHAR(255) NOT NULL, widget_type VARCHAR(50) NOT NULL, datasource_key VARCHAR(255) NOT NULL, question TEXT NOT NULL, sql TEXT NOT NULL, result_mode VARCHAR(50) NOT NULL, position INTEGER NOT NULL, grid_width INTEGER NOT NULL, grid_height INTEGER NOT NULL, active BOOLEAN NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, updated_by VARCHAR(255) NOT NULL, PRIMARY KEY (id), CONSTRAINT uq_overview_widgets_key UNIQUE (widget_key));
CREATE TABLE IF NOT EXISTS prompt_templates (id INTEGER NOT NULL, prompt_key VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, description TEXT NOT NULL, system_prompt TEXT NOT NULL, user_prompt_template TEXT NOT NULL, version INTEGER NOT NULL, active BOOLEAN NOT NULL, updated_by VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, PRIMARY KEY (id), CONSTRAINT uq_prompt_templates_key UNIQUE (prompt_key));
CREATE TABLE IF NOT EXISTS user_datasource_selections (owner_user_id VARCHAR(255) NOT NULL, owner_username VARCHAR(255) NOT NULL, datasource_ids_json TEXT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, PRIMARY KEY (owner_user_id));
CREATE TABLE IF NOT EXISTS user_saved_metrics (id INTEGER NOT NULL, owner_user_id VARCHAR(255) NOT NULL, owner_username VARCHAR(255) NOT NULL, widget_key VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, PRIMARY KEY (id), CONSTRAINT uq_user_saved_metrics_owner_widget UNIQUE (owner_user_id, widget_key));
CREATE TABLE IF NOT EXISTS widget_tags (name VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, PRIMARY KEY (name));
CREATE TABLE IF NOT EXISTS overview_widget_tags (widget_id INTEGER NOT NULL, tag_name VARCHAR(255) NOT NULL, PRIMARY KEY (widget_id, tag_name), FOREIGN KEY(widget_id) REFERENCES overview_widgets (id) ON DELETE CASCADE, FOREIGN KEY(tag_name) REFERENCES widget_tags (name));
CREATE INDEX IF NOT EXISTS ix_admin_audit_logs_action ON admin_audit_logs (action);
CREATE INDEX IF NOT EXISTS ix_admin_audit_logs_actor ON admin_audit_logs (actor);
CREATE INDEX IF NOT EXISTS ix_admin_audit_logs_resource_type ON admin_audit_logs (resource_type);
CREATE INDEX IF NOT EXISTS ix_admin_sessions_auth_provider ON admin_sessions (auth_provider);
CREATE INDEX IF NOT EXISTS ix_admin_sessions_last_seen ON admin_sessions (last_seen);
CREATE INDEX IF NOT EXISTS ix_admin_sessions_role ON admin_sessions (role);
CREATE INDEX IF NOT EXISTS ix_admin_sessions_user_id ON admin_sessions (user_id);
CREATE INDEX IF NOT EXISTS ix_admin_sessions_username ON admin_sessions (username);
CREATE INDEX IF NOT EXISTS ix_admin_users_auth_provider ON admin_users (auth_provider);
CREATE INDEX IF NOT EXISTS ix_admin_users_role ON admin_users (role);
CREATE INDEX IF NOT EXISTS ix_admin_users_username ON admin_users (username);
CREATE INDEX IF NOT EXISTS ix_analysis_sessions_datasource_id ON analysis_sessions (datasource_id);
CREATE INDEX IF NOT EXISTS ix_analysis_sessions_status ON analysis_sessions (status);
CREATE INDEX IF NOT EXISTS ix_analysis_sessions_user_id ON analysis_sessions (user_id);
CREATE INDEX IF NOT EXISTS ix_business_knowledge_claims_connector_id ON business_knowledge_claims (connector_id);
CREATE INDEX IF NOT EXISTS ix_business_knowledge_claims_knowledge_type ON business_knowledge_claims (knowledge_type);
CREATE INDEX IF NOT EXISTS ix_business_knowledge_claims_request_id ON business_knowledge_claims (request_id);
CREATE INDEX IF NOT EXISTS ix_business_knowledge_claims_source ON business_knowledge_claims (source);
CREATE INDEX IF NOT EXISTS ix_business_knowledge_claims_status ON business_knowledge_claims (status);
CREATE INDEX IF NOT EXISTS ix_business_logic_suggestions_connector_id ON business_logic_suggestions (connector_id);
CREATE INDEX IF NOT EXISTS ix_business_logic_suggestions_error_category ON business_logic_suggestions (error_category);
CREATE INDEX IF NOT EXISTS ix_business_logic_suggestions_safety ON business_logic_suggestions (safety);
CREATE INDEX IF NOT EXISTS ix_business_logic_suggestions_status ON business_logic_suggestions (status);
CREATE INDEX IF NOT EXISTS ix_conversation_turns_analysis_session_id ON conversation_turns (analysis_session_id);
CREATE INDEX IF NOT EXISTS ix_conversation_turns_context_decision ON conversation_turns (context_decision);
CREATE INDEX IF NOT EXISTS ix_conversation_turns_conversation_id ON conversation_turns (conversation_id);
CREATE INDEX IF NOT EXISTS ix_conversation_turns_mode ON conversation_turns (mode);
CREATE INDEX IF NOT EXISTS ix_conversation_turns_status ON conversation_turns (status);
CREATE INDEX IF NOT EXISTS ix_conversations_datasource_id ON conversations (datasource_id);
CREATE INDEX IF NOT EXISTS ix_conversations_owner_user_id ON conversations (owner_user_id);
CREATE INDEX IF NOT EXISTS ix_conversations_owner_username ON conversations (owner_username);
CREATE INDEX IF NOT EXISTS ix_conversations_status ON conversations (status);
CREATE INDEX IF NOT EXISTS ix_dashboard_user_states_active_dashboard_id ON dashboard_user_states (active_dashboard_id);
CREATE INDEX IF NOT EXISTS ix_dashboard_user_states_owner_username ON dashboard_user_states (owner_username);
CREATE INDEX IF NOT EXISTS ix_dashboard_shares_access_level ON dashboard_shares (access_level);
CREATE INDEX IF NOT EXISTS ix_dashboard_shares_created_by_user_id ON dashboard_shares (created_by_user_id);
CREATE INDEX IF NOT EXISTS ix_dashboard_shares_created_by_username ON dashboard_shares (created_by_username);
CREATE INDEX IF NOT EXISTS ix_dashboard_shares_dashboard_id ON dashboard_shares (dashboard_id);
CREATE INDEX IF NOT EXISTS ix_dashboard_shares_target_user_id ON dashboard_shares (target_user_id);
CREATE INDEX IF NOT EXISTS ix_dashboard_shares_target_username ON dashboard_shares (target_username);
CREATE INDEX IF NOT EXISTS ix_dashboard_widgets_dashboard_id ON dashboard_widgets (dashboard_id);
CREATE INDEX IF NOT EXISTS ix_dashboard_widgets_metric_widget_key ON dashboard_widgets (metric_widget_key);
CREATE INDEX IF NOT EXISTS ix_dashboard_widgets_owner_user_id ON dashboard_widgets (owner_user_id);
CREATE INDEX IF NOT EXISTS ix_dashboard_widgets_owner_username ON dashboard_widgets (owner_username);
CREATE INDEX IF NOT EXISTS ix_dashboard_widgets_widget_id ON dashboard_widgets (widget_id);
CREATE INDEX IF NOT EXISTS ix_dashboards_owner_user_id ON dashboards (owner_user_id);
CREATE INDEX IF NOT EXISTS ix_dashboards_owner_username ON dashboards (owner_username);
CREATE INDEX IF NOT EXISTS ix_data_query_audit_logs_datasource_id ON data_query_audit_logs (datasource_id);
CREATE INDEX IF NOT EXISTS ix_data_query_audit_logs_output_classification ON data_query_audit_logs (output_classification);
CREATE INDEX IF NOT EXISTS ix_data_query_audit_logs_type ON data_query_audit_logs (type);
CREATE INDEX IF NOT EXISTS ix_data_query_audit_logs_user_id ON data_query_audit_logs (user_id);
CREATE INDEX IF NOT EXISTS ix_datasource_connectors_connector_key ON datasource_connectors (connector_key);
CREATE INDEX IF NOT EXISTS ix_overview_widgets_widget_key ON overview_widgets (widget_key);
CREATE INDEX IF NOT EXISTS ix_prompt_templates_prompt_key ON prompt_templates (prompt_key);
CREATE INDEX IF NOT EXISTS ix_user_datasource_selections_owner_username ON user_datasource_selections (owner_username);
CREATE INDEX IF NOT EXISTS ix_user_saved_metrics_owner_user_id ON user_saved_metrics (owner_user_id);
CREATE INDEX IF NOT EXISTS ix_user_saved_metrics_owner_username ON user_saved_metrics (owner_username);
CREATE INDEX IF NOT EXISTS ix_user_saved_metrics_widget_key ON user_saved_metrics (widget_key);
CREATE TABLE IF NOT EXISTS duckdb_file_imports (id VARCHAR(36) NOT NULL, source_directory VARCHAR(2048) NOT NULL, status VARCHAR(16) NOT NULL, database_url VARCHAR(2048), storage_key VARCHAR(255) NOT NULL, preview_key VARCHAR(255), options_json TEXT NOT NULL, created_at DATETIME NOT NULL, started_at DATETIME, completed_at DATETIME, error_message TEXT, PRIMARY KEY (id), UNIQUE (storage_key));
CREATE INDEX IF NOT EXISTS ix_duckdb_file_imports_status ON duckdb_file_imports(status);
CREATE TABLE IF NOT EXISTS duckdb_file_materializations (datasource_key VARCHAR(255) NOT NULL, materialization_name VARCHAR(255) NOT NULL, import_id VARCHAR(36) NOT NULL, created_at DATETIME NOT NULL, PRIMARY KEY (datasource_key), UNIQUE (materialization_name), UNIQUE (import_id), FOREIGN KEY(import_id) REFERENCES duckdb_file_imports(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS duckdb_file_relations (id INTEGER NOT NULL, import_id VARCHAR(36) NOT NULL, source_file VARCHAR(1024) NOT NULL, source_format VARCHAR(32) NOT NULL, source_member VARCHAR(1024), adapter_key VARCHAR(64) NOT NULL, relation_name VARCHAR(255) NOT NULL, row_count INTEGER NOT NULL, column_count INTEGER NOT NULL, source_size_bytes INTEGER NOT NULL, imported_at DATETIME NOT NULL, PRIMARY KEY (id), FOREIGN KEY(import_id) REFERENCES duckdb_file_imports(id) ON DELETE CASCADE);
CREATE INDEX IF NOT EXISTS ix_duckdb_file_relations_import_id ON duckdb_file_relations(import_id);

-- dialect: postgresql
CREATE TABLE IF NOT EXISTS admin_audit_logs (id SERIAL NOT NULL, occurred_at TIMESTAMP WITH TIME ZONE NOT NULL, actor VARCHAR(255) NOT NULL, action VARCHAR(255) NOT NULL, resource_type VARCHAR(255) NOT NULL, resource_id VARCHAR(255) NOT NULL, details_json TEXT NOT NULL, PRIMARY KEY (id));
CREATE TABLE IF NOT EXISTS admin_sessions (id SERIAL NOT NULL, token_hash VARCHAR(128) NOT NULL, user_id INTEGER NOT NULL, username VARCHAR(255) NOT NULL, role VARCHAR(50) NOT NULL, auth_provider VARCHAR(255) NOT NULL, created_at TIMESTAMP WITH TIME ZONE NOT NULL, last_seen TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY (id));
CREATE UNIQUE INDEX IF NOT EXISTS ix_admin_sessions_token_hash ON admin_sessions (token_hash);
CREATE TABLE IF NOT EXISTS admin_settings ("key" VARCHAR(255) NOT NULL, value TEXT NOT NULL, updated_at TIMESTAMP WITH TIME ZONE NOT NULL, updated_by VARCHAR(255) NOT NULL, PRIMARY KEY ("key"));
CREATE TABLE IF NOT EXISTS admin_users (id SERIAL NOT NULL, username VARCHAR(255) NOT NULL, display_name VARCHAR(255) NOT NULL, auth_provider VARCHAR(255) NOT NULL, role VARCHAR(50) NOT NULL, is_system_admin BOOLEAN NOT NULL, enterprise_access BOOLEAN NOT NULL, password_hash TEXT NOT NULL, must_change_password BOOLEAN NOT NULL, is_provisioned BOOLEAN NOT NULL, created_at TIMESTAMP WITH TIME ZONE NOT NULL, updated_at TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY (id), CONSTRAINT uq_admin_users_auth_provider_username UNIQUE (auth_provider, username));
CREATE TABLE IF NOT EXISTS analysis_sessions (id SERIAL NOT NULL, session_id VARCHAR(64) NOT NULL, status VARCHAR(50) NOT NULL, user_id VARCHAR(255) NOT NULL, datasource_id VARCHAR(255) NOT NULL, question TEXT NOT NULL, context_json TEXT NOT NULL, events_json TEXT NOT NULL, created_at TIMESTAMP WITH TIME ZONE NOT NULL, updated_at TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY (id));
CREATE UNIQUE INDEX IF NOT EXISTS ix_analysis_sessions_session_id ON analysis_sessions (session_id);
CREATE TABLE IF NOT EXISTS business_knowledge_claims (id SERIAL NOT NULL, connector_id INTEGER NOT NULL, knowledge_type VARCHAR(100) NOT NULL, status VARCHAR(50) NOT NULL, claim_text TEXT NOT NULL, subject_json TEXT NOT NULL, evidence_json TEXT NOT NULL, confidence FLOAT NOT NULL, source VARCHAR(100) NOT NULL, request_id VARCHAR(255) NOT NULL, audit_reference VARCHAR(255) NOT NULL, requires_approval BOOLEAN NOT NULL, created_at TIMESTAMP WITH TIME ZONE NOT NULL, last_verified_at TIMESTAMP WITH TIME ZONE, updated_at TIMESTAMP WITH TIME ZONE NOT NULL, updated_by VARCHAR(255) NOT NULL, PRIMARY KEY (id));
CREATE TABLE IF NOT EXISTS business_logic_suggestions (id SERIAL NOT NULL, connector_id INTEGER NOT NULL, source_audit_id INTEGER, status VARCHAR(50) NOT NULL, safety VARCHAR(50) NOT NULL, enabled BOOLEAN NOT NULL, error_category VARCHAR(100) NOT NULL, title VARCHAR(255) NOT NULL, rule_text TEXT NOT NULL, terms_json TEXT NOT NULL, join_hints_json TEXT NOT NULL, failed_identifier VARCHAR(255) NOT NULL, repaired_identifier VARCHAR(255) NOT NULL, confidence FLOAT NOT NULL, created_at TIMESTAMP WITH TIME ZONE NOT NULL, updated_at TIMESTAMP WITH TIME ZONE NOT NULL, updated_by VARCHAR(255) NOT NULL, PRIMARY KEY (id));
CREATE TABLE IF NOT EXISTS conversation_turns (id SERIAL NOT NULL, turn_id VARCHAR(64) NOT NULL, conversation_id VARCHAR(64) NOT NULL, mode VARCHAR(50) NOT NULL, status VARCHAR(50) NOT NULL, original_question TEXT NOT NULL, standalone_question TEXT NOT NULL, answer TEXT NOT NULL, sql TEXT NOT NULL, metadata_json TEXT NOT NULL, data_query_audit_id INTEGER, analysis_session_id VARCHAR(64) NOT NULL, context_decision VARCHAR(50) NOT NULL, context_confidence FLOAT NOT NULL, created_at TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY (id));
CREATE UNIQUE INDEX IF NOT EXISTS ix_conversation_turns_turn_id ON conversation_turns (turn_id);
CREATE TABLE IF NOT EXISTS conversations (id SERIAL NOT NULL, conversation_id VARCHAR(64) NOT NULL, owner_user_id VARCHAR(255) NOT NULL, owner_username VARCHAR(255) NOT NULL, status VARCHAR(50) NOT NULL, datasource_id VARCHAR(255) NOT NULL, datasource_ids_json TEXT NOT NULL, title VARCHAR(255) NOT NULL, summary_json TEXT NOT NULL, created_at TIMESTAMP WITH TIME ZONE NOT NULL, updated_at TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY (id));
CREATE UNIQUE INDEX IF NOT EXISTS ix_conversations_conversation_id ON conversations (conversation_id);
CREATE TABLE IF NOT EXISTS dashboard_user_states (owner_user_id VARCHAR(255) NOT NULL, owner_username VARCHAR(255) NOT NULL, active_dashboard_id VARCHAR(64) NOT NULL, created_at TIMESTAMP WITH TIME ZONE NOT NULL, updated_at TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY (owner_user_id));
CREATE TABLE IF NOT EXISTS dashboard_shares (id SERIAL NOT NULL, dashboard_id VARCHAR(64) NOT NULL, target_user_id VARCHAR(255) NOT NULL, target_username VARCHAR(255) NOT NULL, access_level VARCHAR(20) NOT NULL, created_by_user_id VARCHAR(255) NOT NULL, created_by_username VARCHAR(255) NOT NULL, created_at TIMESTAMP WITH TIME ZONE NOT NULL, updated_at TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY (id), CONSTRAINT uq_dashboard_shares_dashboard_target UNIQUE (dashboard_id, target_user_id));
CREATE TABLE IF NOT EXISTS dashboard_widgets (id SERIAL NOT NULL, widget_id VARCHAR(64) NOT NULL, dashboard_id VARCHAR(64) NOT NULL, owner_user_id VARCHAR(255) NOT NULL, owner_username VARCHAR(255) NOT NULL, metric_widget_key VARCHAR(255) NOT NULL, title VARCHAR(255) NOT NULL, visualization_type VARCHAR(50) NOT NULL, x INTEGER NOT NULL, y INTEGER NOT NULL, w INTEGER NOT NULL, h INTEGER NOT NULL, created_at TIMESTAMP WITH TIME ZONE NOT NULL, updated_at TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY (id), CONSTRAINT uq_dashboard_widgets_widget_id UNIQUE (widget_id));
CREATE TABLE IF NOT EXISTS dashboards (id SERIAL NOT NULL, dashboard_id VARCHAR(64) NOT NULL, owner_user_id VARCHAR(255) NOT NULL, owner_username VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, description TEXT NOT NULL, created_at TIMESTAMP WITH TIME ZONE NOT NULL, updated_at TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY (id));
CREATE UNIQUE INDEX IF NOT EXISTS ix_dashboards_dashboard_id ON dashboards (dashboard_id);
CREATE TABLE IF NOT EXISTS data_query_audit_logs (id SERIAL NOT NULL, occurred_at TIMESTAMP WITH TIME ZONE NOT NULL, type VARCHAR(50) NOT NULL, user_id VARCHAR(255) NOT NULL, datasource_id VARCHAR(255) NOT NULL, question TEXT NOT NULL, answer TEXT NOT NULL, sql TEXT NOT NULL, llm_sql_language VARCHAR(50) NOT NULL, output_classification VARCHAR(50) NOT NULL, metadata_json TEXT NOT NULL, PRIMARY KEY (id), CONSTRAINT data_query_audit_type CHECK (type IN ('info', 'sql_error', 'access_error')), CONSTRAINT output_classification CHECK (output_classification IN ('personal_data', 'sensitive_data', 'technical_data', 'neutral_data', 'unknown')));
CREATE TABLE IF NOT EXISTS database_migration_tags (tag VARCHAR(255) NOT NULL, applied_at TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY (tag));
CREATE TABLE IF NOT EXISTS datasource_connectors (id SERIAL NOT NULL, connector_key VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, database_type VARCHAR(50) NOT NULL, database_url TEXT NOT NULL, sql_dialect VARCHAR(50) NOT NULL, active BOOLEAN NOT NULL, created_at TIMESTAMP WITH TIME ZONE NOT NULL, updated_at TIMESTAMP WITH TIME ZONE NOT NULL, updated_by VARCHAR(255) NOT NULL, PRIMARY KEY (id), CONSTRAINT uq_datasource_connectors_key UNIQUE (connector_key));
UPDATE datasource_connectors SET database_type = 'duckdb-file' WHERE database_type = 'duckdb-excel';
UPDATE datasource_connectors SET database_url = REPLACE(database_url, 'duckdb-excel://', 'duckdb-file://') WHERE database_url LIKE 'duckdb-excel://%';
CREATE TABLE IF NOT EXISTS datasource_schema_caches (connector_id INTEGER NOT NULL, schema_json TEXT NOT NULL, table_settings_json TEXT NOT NULL, formatted_schema TEXT NOT NULL, introspected_at TIMESTAMP WITH TIME ZONE NOT NULL, updated_at TIMESTAMP WITH TIME ZONE NOT NULL, updated_by VARCHAR(255) NOT NULL, PRIMARY KEY (connector_id));
CREATE TABLE IF NOT EXISTS overview_widgets (id SERIAL NOT NULL, widget_key VARCHAR(255) NOT NULL, label VARCHAR(255) NOT NULL, widget_type VARCHAR(50) NOT NULL, datasource_key VARCHAR(255) NOT NULL, question TEXT NOT NULL, sql TEXT NOT NULL, result_mode VARCHAR(50) NOT NULL, position INTEGER NOT NULL, grid_width INTEGER NOT NULL, grid_height INTEGER NOT NULL, active BOOLEAN NOT NULL, created_at TIMESTAMP WITH TIME ZONE NOT NULL, updated_at TIMESTAMP WITH TIME ZONE NOT NULL, updated_by VARCHAR(255) NOT NULL, PRIMARY KEY (id), CONSTRAINT uq_overview_widgets_key UNIQUE (widget_key));
CREATE TABLE IF NOT EXISTS prompt_templates (id SERIAL NOT NULL, prompt_key VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, description TEXT NOT NULL, system_prompt TEXT NOT NULL, user_prompt_template TEXT NOT NULL, version INTEGER NOT NULL, active BOOLEAN NOT NULL, updated_by VARCHAR(255) NOT NULL, created_at TIMESTAMP WITH TIME ZONE NOT NULL, updated_at TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY (id), CONSTRAINT uq_prompt_templates_key UNIQUE (prompt_key));
CREATE TABLE IF NOT EXISTS user_datasource_selections (owner_user_id VARCHAR(255) NOT NULL, owner_username VARCHAR(255) NOT NULL, datasource_ids_json TEXT NOT NULL, created_at TIMESTAMP WITH TIME ZONE NOT NULL, updated_at TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY (owner_user_id));
CREATE TABLE IF NOT EXISTS user_saved_metrics (id SERIAL NOT NULL, owner_user_id VARCHAR(255) NOT NULL, owner_username VARCHAR(255) NOT NULL, widget_key VARCHAR(255) NOT NULL, created_at TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY (id), CONSTRAINT uq_user_saved_metrics_owner_widget UNIQUE (owner_user_id, widget_key));
CREATE TABLE IF NOT EXISTS widget_tags (name VARCHAR(255) NOT NULL, created_at TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY (name));
CREATE TABLE IF NOT EXISTS overview_widget_tags (widget_id INTEGER NOT NULL, tag_name VARCHAR(255) NOT NULL, PRIMARY KEY (widget_id, tag_name), FOREIGN KEY(widget_id) REFERENCES overview_widgets (id) ON DELETE CASCADE, FOREIGN KEY(tag_name) REFERENCES widget_tags (name));
CREATE INDEX IF NOT EXISTS ix_admin_audit_logs_action ON admin_audit_logs (action);
CREATE INDEX IF NOT EXISTS ix_admin_audit_logs_actor ON admin_audit_logs (actor);
CREATE INDEX IF NOT EXISTS ix_admin_audit_logs_resource_type ON admin_audit_logs (resource_type);
CREATE INDEX IF NOT EXISTS ix_admin_sessions_auth_provider ON admin_sessions (auth_provider);
CREATE INDEX IF NOT EXISTS ix_admin_sessions_last_seen ON admin_sessions (last_seen);
CREATE INDEX IF NOT EXISTS ix_admin_sessions_role ON admin_sessions (role);
CREATE INDEX IF NOT EXISTS ix_admin_sessions_user_id ON admin_sessions (user_id);
CREATE INDEX IF NOT EXISTS ix_admin_sessions_username ON admin_sessions (username);
CREATE INDEX IF NOT EXISTS ix_admin_users_auth_provider ON admin_users (auth_provider);
CREATE INDEX IF NOT EXISTS ix_admin_users_role ON admin_users (role);
CREATE INDEX IF NOT EXISTS ix_admin_users_username ON admin_users (username);
CREATE INDEX IF NOT EXISTS ix_analysis_sessions_datasource_id ON analysis_sessions (datasource_id);
CREATE INDEX IF NOT EXISTS ix_analysis_sessions_status ON analysis_sessions (status);
CREATE INDEX IF NOT EXISTS ix_analysis_sessions_user_id ON analysis_sessions (user_id);
CREATE INDEX IF NOT EXISTS ix_business_knowledge_claims_connector_id ON business_knowledge_claims (connector_id);
CREATE INDEX IF NOT EXISTS ix_business_knowledge_claims_knowledge_type ON business_knowledge_claims (knowledge_type);
CREATE INDEX IF NOT EXISTS ix_business_knowledge_claims_request_id ON business_knowledge_claims (request_id);
CREATE INDEX IF NOT EXISTS ix_business_knowledge_claims_source ON business_knowledge_claims (source);
CREATE INDEX IF NOT EXISTS ix_business_knowledge_claims_status ON business_knowledge_claims (status);
CREATE INDEX IF NOT EXISTS ix_business_logic_suggestions_connector_id ON business_logic_suggestions (connector_id);
CREATE INDEX IF NOT EXISTS ix_business_logic_suggestions_error_category ON business_logic_suggestions (error_category);
CREATE INDEX IF NOT EXISTS ix_business_logic_suggestions_safety ON business_logic_suggestions (safety);
CREATE INDEX IF NOT EXISTS ix_business_logic_suggestions_status ON business_logic_suggestions (status);
CREATE INDEX IF NOT EXISTS ix_conversation_turns_analysis_session_id ON conversation_turns (analysis_session_id);
CREATE INDEX IF NOT EXISTS ix_conversation_turns_context_decision ON conversation_turns (context_decision);
CREATE INDEX IF NOT EXISTS ix_conversation_turns_conversation_id ON conversation_turns (conversation_id);
CREATE INDEX IF NOT EXISTS ix_conversation_turns_mode ON conversation_turns (mode);
CREATE INDEX IF NOT EXISTS ix_conversation_turns_status ON conversation_turns (status);
CREATE INDEX IF NOT EXISTS ix_conversations_datasource_id ON conversations (datasource_id);
CREATE INDEX IF NOT EXISTS ix_conversations_owner_user_id ON conversations (owner_user_id);
CREATE INDEX IF NOT EXISTS ix_conversations_owner_username ON conversations (owner_username);
CREATE INDEX IF NOT EXISTS ix_conversations_status ON conversations (status);
CREATE INDEX IF NOT EXISTS ix_dashboard_user_states_active_dashboard_id ON dashboard_user_states (active_dashboard_id);
CREATE INDEX IF NOT EXISTS ix_dashboard_user_states_owner_username ON dashboard_user_states (owner_username);
CREATE INDEX IF NOT EXISTS ix_dashboard_shares_access_level ON dashboard_shares (access_level);
CREATE INDEX IF NOT EXISTS ix_dashboard_shares_created_by_user_id ON dashboard_shares (created_by_user_id);
CREATE INDEX IF NOT EXISTS ix_dashboard_shares_created_by_username ON dashboard_shares (created_by_username);
CREATE INDEX IF NOT EXISTS ix_dashboard_shares_dashboard_id ON dashboard_shares (dashboard_id);
CREATE INDEX IF NOT EXISTS ix_dashboard_shares_target_user_id ON dashboard_shares (target_user_id);
CREATE INDEX IF NOT EXISTS ix_dashboard_shares_target_username ON dashboard_shares (target_username);
CREATE INDEX IF NOT EXISTS ix_dashboard_widgets_dashboard_id ON dashboard_widgets (dashboard_id);
CREATE INDEX IF NOT EXISTS ix_dashboard_widgets_metric_widget_key ON dashboard_widgets (metric_widget_key);
CREATE INDEX IF NOT EXISTS ix_dashboard_widgets_owner_user_id ON dashboard_widgets (owner_user_id);
CREATE INDEX IF NOT EXISTS ix_dashboard_widgets_owner_username ON dashboard_widgets (owner_username);
CREATE INDEX IF NOT EXISTS ix_dashboard_widgets_widget_id ON dashboard_widgets (widget_id);
CREATE INDEX IF NOT EXISTS ix_dashboards_owner_user_id ON dashboards (owner_user_id);
CREATE INDEX IF NOT EXISTS ix_dashboards_owner_username ON dashboards (owner_username);
CREATE INDEX IF NOT EXISTS ix_data_query_audit_logs_datasource_id ON data_query_audit_logs (datasource_id);
CREATE INDEX IF NOT EXISTS ix_data_query_audit_logs_output_classification ON data_query_audit_logs (output_classification);
CREATE INDEX IF NOT EXISTS ix_data_query_audit_logs_type ON data_query_audit_logs (type);
CREATE INDEX IF NOT EXISTS ix_data_query_audit_logs_user_id ON data_query_audit_logs (user_id);
CREATE INDEX IF NOT EXISTS ix_datasource_connectors_connector_key ON datasource_connectors (connector_key);
CREATE INDEX IF NOT EXISTS ix_overview_widgets_widget_key ON overview_widgets (widget_key);
CREATE INDEX IF NOT EXISTS ix_prompt_templates_prompt_key ON prompt_templates (prompt_key);
CREATE INDEX IF NOT EXISTS ix_user_datasource_selections_owner_username ON user_datasource_selections (owner_username);
CREATE INDEX IF NOT EXISTS ix_user_saved_metrics_owner_user_id ON user_saved_metrics (owner_user_id);
CREATE INDEX IF NOT EXISTS ix_user_saved_metrics_owner_username ON user_saved_metrics (owner_username);
CREATE INDEX IF NOT EXISTS ix_user_saved_metrics_widget_key ON user_saved_metrics (widget_key);
CREATE TABLE IF NOT EXISTS duckdb_file_imports (id VARCHAR(36) NOT NULL, source_directory VARCHAR(2048) NOT NULL, status VARCHAR(16) NOT NULL, database_url VARCHAR(2048), storage_key VARCHAR(255) NOT NULL, preview_key VARCHAR(255), options_json TEXT NOT NULL, created_at TIMESTAMP WITH TIME ZONE NOT NULL, started_at TIMESTAMP WITH TIME ZONE, completed_at TIMESTAMP WITH TIME ZONE, error_message TEXT, PRIMARY KEY (id), UNIQUE (storage_key));
CREATE INDEX IF NOT EXISTS ix_duckdb_file_imports_status ON duckdb_file_imports(status);
CREATE TABLE IF NOT EXISTS duckdb_file_materializations (datasource_key VARCHAR(255) NOT NULL, materialization_name VARCHAR(255) NOT NULL, import_id VARCHAR(36) NOT NULL, created_at TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY (datasource_key), UNIQUE (materialization_name), UNIQUE (import_id), FOREIGN KEY(import_id) REFERENCES duckdb_file_imports(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS duckdb_file_relations (id SERIAL PRIMARY KEY, import_id VARCHAR(36) NOT NULL, source_file VARCHAR(1024) NOT NULL, source_format VARCHAR(32) NOT NULL, source_member VARCHAR(1024), adapter_key VARCHAR(64) NOT NULL, relation_name VARCHAR(255) NOT NULL, row_count INTEGER NOT NULL, column_count INTEGER NOT NULL, source_size_bytes INTEGER NOT NULL, imported_at TIMESTAMP WITH TIME ZONE NOT NULL, FOREIGN KEY(import_id) REFERENCES duckdb_file_imports(id) ON DELETE CASCADE);
CREATE INDEX IF NOT EXISTS ix_duckdb_file_relations_import_id ON duckdb_file_relations(import_id);
