from typing import Any, Protocol

from gaard_core.prompt_compiler.models import CompiledPrompt, SqlGenerationPromptRequest
from gaard_core.prompt_compiler.sql_generation_prompt import SqlGenerationPromptCompiler
from gaard_core.llm_output import remove_thinking_blocks
from gaard_core.query_pipeline.models import GeneratedSql, QueryRequest
from gaard_llm.openai_compatible.client import OpenAICompatibleClient
from gaard_llm.providers.models import ChatCompletionRequest, ChatMessage


class SqlPromptCompiler(Protocol):
    def compile(self, request: SqlGenerationPromptRequest) -> CompiledPrompt:
        pass


class LlmSqlGenerator:
    def __init__(
        self,
        client: OpenAICompatibleClient,
        model: str,
        formatted_schema: str,
        dialect: str = "sqlite",
        max_rows: int = 100,
        extra_body: dict[str, Any] | None = None,
        prompt_compiler: SqlPromptCompiler | None = None,
    ) -> None:
        self.client = client
        self.model = model
        self.formatted_schema = formatted_schema
        self.dialect = dialect
        self.max_rows = max_rows
        self.extra_body = extra_body or {}
        self.prompt_compiler = prompt_compiler or SqlGenerationPromptCompiler()

    def generate(self, request: QueryRequest) -> GeneratedSql:
        compiled_prompt = self.prompt_compiler.compile(
            SqlGenerationPromptRequest(
                question=request.question,
                formatted_schema=self.formatted_schema,
                dialect=self.dialect,
                max_rows=self.max_rows,
            )
        )

        response = self.client.create_chat_completion(
            ChatCompletionRequest(
                model=self.model,
                temperature=0.0,
                extra_body=self.extra_body,
                messages=[
                    ChatMessage(
                        role="system",
                        content=compiled_prompt.system_prompt,
                    ),
                    ChatMessage(
                        role="user",
                        content=compiled_prompt.user_prompt,
                    ),
                ],
            )
        )

        sql = self._clean_sql(response.content)

        return GeneratedSql(
            sql=sql,
            confidence=0.0,
            assumptions=[
                "SQL generated by OpenAI-compatible LLM provider.",
            ],
        )

    def _clean_sql(self, value: str) -> str:
        cleaned = remove_thinking_blocks(value)

        if cleaned.startswith("```sql"):
            cleaned = cleaned.removeprefix("```sql").strip()

        if cleaned.startswith("```"):
            cleaned = cleaned.removeprefix("```").strip()

        if cleaned.endswith("```"):
            cleaned = cleaned.removesuffix("```").strip()

        return cleaned
